#!/bin/bash

#PBS -l walltime=01:00:00
#PBS -l mem=50GB
#PBS -l ncpus=1
#PBS -l jobfs=1GB
#PBS -l storage=gdata/hh5+scratch/k10+scratch/gb02
#PBS -q normal
#PBS -P nf33
#PBS -o /scratch/k10/mr4682/hk25-AusNode-ConvTrop/examples/calc_clim_olr.out
#PBS -e /scratch/k10/mr4682/hk25-AusNode-ConvTrop/examples/calc_clim_olr.err

cd /scratch/k10/mr4682/hk25-AusNode-ConvTrop/

source ./env.sh

python examples/calc_clim_olr.py
