#!/bin/bash
  
#PBS -l walltime=02:00:00
#PBS -l mem=100GB
#PBS -l ncpus=1
#PBS -l jobfs=1GB
#PBS -l storage=gdata/xp65+scratch/nf33+scratch/gb02+gdata/qx55+scratch/k10
#PBS -q normal
#PBS -P nf33
#PBS -o /scratch/k10/mr4682/hk25-AusNode-ConvTrop/scripts/calc_composite_rlut_anom_moisture_mode_EQ_ALL.out
#PBS -e /scratch/k10/mr4682/hk25-AusNode-ConvTrop/scripts/calc_composite_rlut_anom_moisture_mode_EQ_ALL.err

cd /scratch/k10/mr4682/hk25-AusNode-ConvTrop/

source ./env.sh

python scripts/calc_composite.py
