#!/bin/bash
  
#PBS -l walltime=02:00:00
#PBS -l mem=100GB
#PBS -l ncpus=4
#PBS -l jobfs=1GB
#PBS -l storage=gdata/hh5+scratch/nf33+scratch/gb02+gdata/qx55
#PBS -q normal
#PBS -P nf33
#PBS -o /home/561/tp4064/hk25-AusNode-ConvTrop/scripts/um_10_regrid_va.out
#PBS -e /home/561/tp4064/hk25-AusNode-ConvTrop/scripts/um_10_regrid_va.err

cd /home/561/tp4064/hk25-AusNode-ConvTrop/

source ./env.sh

python scripts/regrid.py
